Since selection is using precomputed dependences generated by prioritization/parallelization, 
there is no "third" program for an enhanced selection. Enhanced selection instead is just 
using the precomputed dependences from the other two techniques and seeing how useful they are
to normal selection.